export const SAVE_FORECAST_ROUTE = "SAVE_FORECAST_ROUTE";
export const SAVE_WEATHER_DATA = "SAVE_WEATHER_DATA";
export const SAVE_WEATHER_DATA_LOADER = "SAVE_WEATHER_DATA_LOADER";
export const SAVE_FINAL_DATA_WITH_DAYS_ADDED =
  "SAVE_FINAL_DATA_WITH_DAYS_ADDED";
