export const REGISTER_USER = "REGISTER_USER";
export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";
export const LOGIN_USER = "LOGIN_USER";
export const IS_LOGIN = "IS_LOGIN";
export const SET_CURRENT_USER = "CARATFLARE/USER0/SET_CURRENT_USER";
